[package]
name = "gfx_font_cache" # TODO: rename
version = "0.1.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]

[dependencies]
rusttype = "*"
unicode-normalization = "*"
gfx = "*"
gfx_core = "*"
gfx_window_glutin = "*"

# TODO: remove this
gfx_device_gl = "*"
glutin = "*"
